### ISSUE TITLE
Dist possibly broken by Mojolicious v9 changes

### ISSUE THREAD

**Issue by leejo** [powerman/perl-MojoX-JSONRPC2-HTTP#1]
As per: https://github.com/mojolicious/mojo/wiki/Upgrading

lib code and/or tests in this distribution appears to use one or more of: via, over, detour, route

It's likely this dist will no longer work with Mojolicious v9 - check the aforementioned link for upgrade details.

Thanks!
Lee.

**Comment by powerman** [comment]
Fixed in v2.0.2.
